// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectMasters.Data;

namespace ProjectMasters.Migrations
{
    [DbContext(typeof(ProjectMastersContext))]
    [Migration("20200731071530_AddProjectFeatures")]
    partial class AddProjectFeatures
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectMasters.Models.Feature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Feature");
                });

            modelBuilder.Entity("ProjectMasters.Models.FeatureTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Estimate")
                        .HasColumnType("real");

                    b.Property<long?>("FeatureId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FeatureTaskId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Progress")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("FeatureTaskId");

                    b.ToTable("FeatureTask");
                });

            modelBuilder.Entity("ProjectMasters.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("ProjectMasters.Models.SkillScheme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("FeatureTaskId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureTaskId");

                    b.ToTable("SkillScheme");
                });

            modelBuilder.Entity("ProjectMasters.Models.Feature", b =>
                {
                    b.HasOne("ProjectMasters.Models.Project", null)
                        .WithMany("Features")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("ProjectMasters.Models.FeatureTask", b =>
                {
                    b.HasOne("ProjectMasters.Models.Feature", null)
                        .WithMany("Tasks")
                        .HasForeignKey("FeatureId");

                    b.HasOne("ProjectMasters.Models.FeatureTask", null)
                        .WithMany("Blockers")
                        .HasForeignKey("FeatureTaskId");
                });

            modelBuilder.Entity("ProjectMasters.Models.SkillScheme", b =>
                {
                    b.HasOne("ProjectMasters.Models.FeatureTask", null)
                        .WithMany("RequiredSkills")
                        .HasForeignKey("FeatureTaskId");
                });
#pragma warning restore 612, 618
        }
    }
}
