// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectMasters.Data;

namespace ProjectMasters.Migrations
{
    [DbContext(typeof(ProjectMastersContext))]
    partial class ProjectMastersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectMasters.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("FeatureTaskId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureTaskId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("ProjectMasters.Models.Feature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Feature");
                });

            modelBuilder.Entity("ProjectMasters.Models.FeatureTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Estimate")
                        .HasColumnType("real");

                    b.Property<long?>("FeatureId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FeatureTaskId")
                        .HasColumnType("bigint");

                    b.Property<float>("Logged")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Progress")
                        .HasColumnType("real");

                    b.Property<float>("RealValue")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("FeatureTaskId");

                    b.ToTable("FeatureTask");
                });

            modelBuilder.Entity("ProjectMasters.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("ProjectMasters.Models.RequiredSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("FeatureTaskId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SkillSchemeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeatureTaskId");

                    b.HasIndex("SkillSchemeId");

                    b.ToTable("RequiredSkill");
                });

            modelBuilder.Entity("ProjectMasters.Models.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SchemeId")
                        .HasColumnType("bigint");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SchemeId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("ProjectMasters.Models.SkillScheme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkillSchemes");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = -2L,
                            Name = "Backend"
                        },
                        new
                        {
                            Id = -3L,
                            Name = "Mobile"
                        });
                });

            modelBuilder.Entity("ProjectMasters.Models.Employee", b =>
                {
                    b.HasOne("ProjectMasters.Models.FeatureTask", null)
                        .WithMany("Assignees")
                        .HasForeignKey("FeatureTaskId");
                });

            modelBuilder.Entity("ProjectMasters.Models.Feature", b =>
                {
                    b.HasOne("ProjectMasters.Models.Project", null)
                        .WithMany("Features")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("ProjectMasters.Models.FeatureTask", b =>
                {
                    b.HasOne("ProjectMasters.Models.Feature", null)
                        .WithMany("Tasks")
                        .HasForeignKey("FeatureId");

                    b.HasOne("ProjectMasters.Models.FeatureTask", null)
                        .WithMany("Blockers")
                        .HasForeignKey("FeatureTaskId");
                });

            modelBuilder.Entity("ProjectMasters.Models.RequiredSkill", b =>
                {
                    b.HasOne("ProjectMasters.Models.FeatureTask", null)
                        .WithMany("RequiredSkills")
                        .HasForeignKey("FeatureTaskId");

                    b.HasOne("ProjectMasters.Models.SkillScheme", "SkillScheme")
                        .WithMany()
                        .HasForeignKey("SkillSchemeId");
                });

            modelBuilder.Entity("ProjectMasters.Models.Skill", b =>
                {
                    b.HasOne("ProjectMasters.Models.Employee", null)
                        .WithMany("Skills")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("ProjectMasters.Models.SkillScheme", "Scheme")
                        .WithMany()
                        .HasForeignKey("SchemeId");
                });
#pragma warning restore 612, 618
        }
    }
}
